{
  "compatibilityLevel": 1601,
  "model": {
    "culture": "es-ES",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "es-ES",
    "tables": [
      {
        "name": "recomendaciones_finales",
        "columns": [
          { "name": "rank", "dataType": "int64", "sourceColumn": "rank", "summarizeBy": "none" },
          { "name": "movieId", "dataType": "int64", "sourceColumn": "movieId", "summarizeBy": "none" },
          { "name": "title", "dataType": "string", "sourceColumn": "title" },
          { "name": "year", "dataType": "int64", "sourceColumn": "year", "summarizeBy": "none" },
          { "name": "decade", "dataType": "int64", "sourceColumn": "decade", "summarizeBy": "none" },
          { "name": "genres", "dataType": "string", "sourceColumn": "genres" },
          { "name": "main_genre", "dataType": "string", "sourceColumn": "main_genre" },
          { "name": "final_recommendation_score", "dataType": "double", "sourceColumn": "final_recommendation_score" },
          { "name": "recommendation_bucket", "dataType": "string", "sourceColumn": "recommendation_bucket" },
          { "name": "recommendation_bucket_label", "dataType": "string", "sourceColumn": "recommendation_bucket_label" },
          { "name": "recommendation_branch", "dataType": "string", "sourceColumn": "recommendation_branch" },
          { "name": "dominant_signal", "dataType": "string", "sourceColumn": "dominant_signal" },
          { "name": "dominant_signal_label", "dataType": "string", "sourceColumn": "dominant_signal_label" },
          { "name": "explanation_display", "dataType": "string", "sourceColumn": "explanation_display" },
          { "name": "anchor_movies_matched", "dataType": "string", "sourceColumn": "anchor_movies_matched" },
          { "name": "false_positive_risk", "dataType": "double", "sourceColumn": "false_positive_risk" },
          { "name": "preference_margin_score", "dataType": "double", "sourceColumn": "preference_margin_score" },
          { "name": "user_temporal_affinity_score", "dataType": "double", "sourceColumn": "user_temporal_affinity_score" },
          { "name": "temporal_affinity_label", "dataType": "string", "sourceColumn": "temporal_affinity_label" },
          { "name": "rating_score", "dataType": "double", "sourceColumn": "rating_score" },
          { "name": "popularity_score", "dataType": "double", "sourceColumn": "popularity_score" },
          { "name": "hybrid_score", "dataType": "double", "sourceColumn": "hybrid_score" },
          { "name": "human_like_v3_adjusted_score", "dataType": "double", "sourceColumn": "human_like_v3_adjusted_score" }
        ],
        "partitions": [
          {
            "name": "recomendaciones_finales",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\alexo\\\\Desktop\\\\TFG\\\\powerbi\\\\datasets\\\\recomendaciones_finales.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"rank\", Int64.Type}, {\"movieId\", Int64.Type}, {\"title\", type text}, {\"year\", Int64.Type}, {\"decade\", Int64.Type}, {\"genres\", type text}, {\"main_genre\", type text}, {\"final_recommendation_score\", type number}, {\"recommendation_bucket\", type text}, {\"recommendation_bucket_label\", type text}, {\"recommendation_branch\", type text}, {\"dominant_signal\", type text}, {\"dominant_signal_label\", type text}, {\"explanation_display\", type text}, {\"anchor_movies_matched\", type text}, {\"false_positive_risk\", type number}, {\"preference_margin_score\", type number}, {\"user_temporal_affinity_score\", type number}, {\"temporal_affinity_label\", type text}, {\"rating_score\", type number}, {\"popularity_score\", type number}, {\"hybrid_score\", type number}, {\"human_like_v3_adjusted_score\", type number}})",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "perfil_usuario_trakt",
        "columns": [
          { "name": "movieId", "dataType": "int64", "sourceColumn": "movieId", "summarizeBy": "none" },
          { "name": "title", "dataType": "string", "sourceColumn": "title" },
          { "name": "year", "dataType": "int64", "sourceColumn": "year", "summarizeBy": "none" },
          { "name": "decade", "dataType": "int64", "sourceColumn": "decade", "summarizeBy": "none" },
          { "name": "genres", "dataType": "string", "sourceColumn": "genres" },
          { "name": "main_genre", "dataType": "string", "sourceColumn": "main_genre" },
          { "name": "trakt_rating", "dataType": "double", "sourceColumn": "trakt_rating" },
          { "name": "user_rating_5", "dataType": "double", "sourceColumn": "user_rating_5" },
          { "name": "watched", "dataType": "boolean", "sourceColumn": "watched" },
          { "name": "rated", "dataType": "boolean", "sourceColumn": "rated" },
          { "name": "profile_type", "dataType": "string", "sourceColumn": "profile_type" },
          { "name": "source", "dataType": "string", "sourceColumn": "source" }
        ],
        "partitions": [
          {
            "name": "perfil_usuario_trakt",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\alexo\\\\Desktop\\\\TFG\\\\powerbi\\\\datasets\\\\perfil_usuario_trakt.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"movieId\", Int64.Type}, {\"title\", type text}, {\"year\", Int64.Type}, {\"decade\", Int64.Type}, {\"genres\", type text}, {\"main_genre\", type text}, {\"trakt_rating\", type number}, {\"user_rating_5\", type number}, {\"watched\", type logical}, {\"rated\", type logical}, {\"profile_type\", type text}, {\"source\", type text}})",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "metricas_recomendador",
        "columns": [
          { "name": "metric", "dataType": "string", "sourceColumn": "metric" },
          { "name": "value", "dataType": "string", "sourceColumn": "value" }
        ],
        "measures": [
          { "name": "total_recommendations", "expression": "VALUE(LOOKUPVALUE(metricas_recomendador[value], metricas_recomendador[metric], \"total_recommendations\"))", "formatString": "0" },
          { "name": "total_candidates", "expression": "VALUE(LOOKUPVALUE(metricas_recomendador[value], metricas_recomendador[metric], \"total_candidates\"))", "formatString": "0" },
          { "name": "trakt_ratings_mapped", "expression": "VALUE(LOOKUPVALUE(metricas_recomendador[value], metricas_recomendador[metric], \"trakt_ratings_mapped\"))", "formatString": "0" },
          { "name": "trakt_watched_mapped", "expression": "VALUE(LOOKUPVALUE(metricas_recomendador[value], metricas_recomendador[metric], \"trakt_watched_mapped\"))", "formatString": "0" },
          { "name": "false_positive_risk_mean", "expression": "VALUE(LOOKUPVALUE(metricas_recomendador[value], metricas_recomendador[metric], \"false_positive_risk_mean\"))", "formatString": "0.0000" }
        ],
        "partitions": [
          {
            "name": "metricas_recomendador",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\alexo\\\\Desktop\\\\TFG\\\\powerbi\\\\datasets\\\\metricas_recomendador.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"metric\", type text}, {\"value\", type text}})",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      },
      {
        "name": "distribucion_recomendaciones",
        "columns": [
          { "name": "dimension", "dataType": "string", "sourceColumn": "dimension" },
          { "name": "category", "dataType": "string", "sourceColumn": "category" },
          { "name": "count", "dataType": "int64", "sourceColumn": "count" },
          { "name": "percentage", "dataType": "double", "sourceColumn": "percentage" }
        ],
        "partitions": [
          {
            "name": "distribucion_recomendaciones",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\\\Users\\\\alexo\\\\Desktop\\\\TFG\\\\powerbi\\\\datasets\\\\distribucion_recomendaciones.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{\"dimension\", type text}, {\"category\", type text}, {\"count\", Int64.Type}, {\"percentage\", type number}})",
                "in",
                "    ChangedType"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [],
    "annotations": [
      {
        "name": "PBIPStarterNote",
        "value": "Modelo generado programaticamente desde CSV locales. No crea relaciones para evitar filtrados incorrectos."
      }
    ]
  }
}
